### ISSUE TITLE
Add good first issue link

### ISSUE THREAD

**Issue by millnut** [localgovdrupal/localgov_repos#3]
We should have a link/button where people can quickly view "good first issue" issues to help them start contributing 

https://github.com/issues?q=is%3Aissue+user%3Alocalgovdrupal+is%3Aopen+label%3A%22good+first+issue%22+

**Comment by markconroy** [comment]
Done, thanks for the sugestion: https://github.com/localgovdrupal/localgov_repos/commit/6a20b76e031d5dad967f26bcc54d289d038f32d9
